ptm/Django_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include ,re_path
from django.conf import settings
from django.conf.urls.static import static
from mysite.admin import my_admin_site
from functionality import views as funcviews

urlpatterns = [
    path('admin/', my_admin_site.urls),
    url(r'', include('mysite.urls')),
    path('search', funcviews.search2 , name='search'),
    path('new-property', funcviews.createproperty , name='new-property'),
    path('property-detail/<int:id>', funcviews.propertydetail , name='property-detail'),
    path('add-to-list/<int:listid>/<int:objid>', funcviews.addtolist , name='add-to-list'),
    path('delete-list/<int:id>', funcviews.deletelist , name='delete-list'),
    path('remove-from-list/<int:listid>/<int:objid>', funcviews.removefromlist , name='remove-from-list'),
    path('manage-lists', funcviews.managelists , name='manage-lists'),
    path('create-list', funcviews.createlist , name='create-list'),
    path('name-list/<str:name>/<int:proid>', funcviews.namelist, name='name-list'),
    path('show-list/<int:id>', funcviews.showlist , name='show-list'),
    path('request-tour/<int:listid>/<int:proid>/<int:reqid>', funcviews.requesttour , name='request-tour'),
    path('submit-request/<int:reqid>', funcviews.submitrequest, name='submit-request'),
    path('remove-from-tour/<int:proid>/<int:reqid>', funcviews.removefromtour, name='remove-from-tour'),
    path('show-tour/<int:reqid>', funcviews.showtour, name='show-tour'),
    path('add-note/<int:id>', funcviews.addnote , name='add-note'),
    path('tour-requests', funcviews.toursrequested , name='tour-requests'),
    path('add-to-tour/<int:tid>/<int:proid>', funcviews.addtotour, name='add-to-tour'),
    path('show-notes', funcviews.shownotes , name='show-notes'),
    path('reply-to-note/<int:id>', funcviews.replytonote, name='reply-to-note'),
    path('listnotechange/<int:id>', funcviews.listnotechange, name='listnotechange'),
    path('addfromlist/<int:listid>/<int:proid>/<int:currentid>', funcviews.addfromlist, name='addfromlist'),
    path('listofbuyers', funcviews.listofbuyers, name='listofbuyers'),
    path('approve-tour/<int:id>', funcviews.approvetour, name='approve-tour'),
    path('cancel-tour/<int:id>', funcviews.canceltour, name='cancel-tour'),
    path('createtour', funcviews.createtour , name='create-tour'),
    path('delete-tour/<int:id>', funcviews.deletetour , name='delete-tour'),
    path('offer/<int:id>', funcviews.offer , name='offer'),
    path('offers', funcviews.agent_offercheck , name='offers'),
    path('tour/<int:id>', funcviews.tour, name='tour'),
    path('changestatus/<str:id>/<int:id2>', funcviews.changeofferstatus),
    path('profile/<str:usr>', funcviews.profilepage, name='profile'),
    path('share-list/<str:usr>/<int:id>', funcviews.sharelist),
    path('share-list-buyer/<str:usr>/<int:id>', funcviews.sharelistbuyer),
    path('unlink/<int:id>', funcviews.unlinklist),
    path('rate/<int:listid>/<int:proid>/<int:rating>', funcviews.ratepro),
]


if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ptm/mysite/urls.py
from django.conf.urls import url
from django.urls import path , include
from . import views
#REST API URLS


from django.contrib.auth.views import PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
 
    url(r'^$', views.home, name="home"),
    url(r'login/', views.login_user, name = 'login'),
    url(r'^logout/$', views.logout_user, name= "logout"),
    url(r'^register/$', views.register_user, name= "register"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    url(r'edit-profile/$', views.edit_profile, name="editProfile"),
    url(r'edit-profile-inform/$', views.edit_profile_user, name="editProfileUSer"),

    #Password Change URL............
    url(r'^change_password/$', views.change_password, name = "change_password"),

    #password Reset URLS...........
    path('password_reset/', PasswordResetView.as_view(), name='password_reset' ),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('contact/', views.contact, name= "contact"),



    path('get-all-data/<int:sel>/<str:val>', views.newfunc),
    path('get-all-data-buyer/<int:sel>/<str:val>/<str:usr>', views.newfunc2),

    

    






  
  

  
]

ptm/mysite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib.auth import get_user_model

CHOICES_TYPE = (
    ('Buyer', 'Buyer'),
    ('Agent', 'Agent')
)

choice1 =(('Short Commute to work','Short Commute to work'),
          ('Access to shopping','Access to shopping'),
          ('Vastu Preference','Vastu Preference'),
          ('School Requirements','School Requirements'),
           )


class profileModel(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete= models.CASCADE)
    approve = models.BooleanField(default=True)
    Teacher_or_Parent = models.CharField(max_length=10, blank=True, default='Buyer' ,choices=CHOICES_TYPE)
    phone=models.CharField(max_length=11,blank=True,null=True, default='')
    occupation=models.CharField(max_length=200,blank=True,null=True, default='')
    #Property Requirements
    minprice = models.IntegerField(default=0)
    maxprice = models.IntegerField(default=0)
    minsqft = models.IntegerField(default=0)
    maxsqft = models.IntegerField(default=0)
    has_pre_approval=models.CharField(max_length=200,blank=True,null=True)
    property_type=models.CharField(max_length=200,blank=True,null=True)
    beds=models.CharField(max_length=200,blank=True,null=True)
    bath=models.CharField(max_length=200,blank=True,null=True)
    minlot = models.IntegerField(default=0)
    maxlot = models.IntegerField(default=0)
    stories=models.CharField(max_length=200,blank=True,null=True)
    location_preference=models.CharField(max_length=200,blank=True,null=True)
    looking_to_buy_in_how_many_months=models.CharField(max_length=200,blank=True,null=True)
    How_long_have_you_been_house_hunting=models.CharField(max_length=200,blank=True,null=True)
    Life_style = models.CharField(max_length=200,blank=True,null=True,choices=choice1)
    any_other = models.CharField(max_length=200,blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

ptm/mysite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import *
from django.contrib.auth import (authenticate, get_user_model, password_validation,)


#User Login Form ................
class loginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())



#User Registration Form...................
class registerForm(forms.ModelForm):
    password = forms.CharField(label = 'Password', widget = forms.PasswordInput(),strip=False,help_text=password_validation.password_validators_help_text_html(),)
    password2 = forms.CharField(label = 'Repeat Password', widget = forms.PasswordInput(),strip=False,help_text="Both Passwords should be same.",)
    email = forms.EmailField(label = 'Email Address', widget = forms.TextInput())
    class Meta:
        model = User
        fields = [
            'username',
           
         
        ]
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        
        emails=User.objects.all()
        for i in emails:
            if email==i.email:
    
                raise forms.ValidationError('This email already exists, check your email') 

        return email

    #Cleaning Method for password Match..........
    def clean_password2(self):
        cd = self.cleaned_data
        if self.cleaned_data.get('password') != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']

    #Cleaning Method for Email Unique..........
    def clean(self):
        if self.cleaned_data.get('email') is None:
            raise ValidationError("Enter a valid E-mail Address")
        varEmail = self.cleaned_data.get('email').lower()
        if User.objects.filter(email = varEmail).count() != 0 :
            if not User.objects.get(email = varEmail).is_active :
                User.objects.get(email = varEmail).delete()
            else:
                raise ValidationError(self.cleaned_data.get('email') + "\tAlready Exists.")
###
class contactForm(forms.Form):
    userName =  forms.CharField(label='', widget = forms.TextInput(attrs = {'placeholder' : 'Name'}))    
    email = forms.EmailField(label = '', widget = forms.TextInput(attrs = {'placeholder' : 'Email'}))
    body = forms.CharField(label='', widget=forms.Textarea(attrs = {'placeholder':'Message', 'cols' : '30', 'rows' : '10'}))




#User Extra Information ................
class profileInformForm(forms.ModelForm):
    class Meta:
        model = profileModel
        exclude=['user','approve','Teacher_or_Parent']


#User Extra Information During registration ................
class profileInformFormRegister(forms.ModelForm):
    class Meta:
        model = profileModel
        fields = [
            'phone',
            'occupation'
        ]

    def clean_phone(self):
        if self.cleaned_data.get('phone') is not None:
            try:
                int(self.cleaned_data.get('phone'), base=10)
            except:
                raise ValidationError("Phone Number is not valid.")
            # if len(self.cleaned_data.get('phone')) <= 11:
            #     raise ValidationError("Phone Number is not valid")
        return self.cleaned_data.get('phone')

    def clean_occupation(self):
        return self.cleaned_data.get('occupation')


#User Can Edit his profile using this Form..........................
class EditProfileForm(UserChangeForm):
    password = forms.CharField(label='', widget = forms.TextInput(attrs = {'type' : 'hidden'}))
    class Meta:
        model = User
        fields = [
                  'first_name',
                  'last_name',
                  'password',
                  'email'
                  ]

ptm/mysite/templates/mysite/Approve.html
{% extends 'base.html' %}

{% block content %}

<center><h1> Approval Pending</h1></center>
<center><p>Your account needs approval from manager, please wait for 24hours</p></center>

{% endblock %}

ptm/mysite/templates/mysite/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

ptm/mysite/templates/mysite/acc_active_email_confirm.html
{% extends "base.html" %}
{% load static %}
{% block title %}Email Verification{% endblock %}







{% block register %}
<div class="register-login-area">
                            
        <a href="{% url 'register' %}" class="btn active">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endblock  %}




{% block content %}
  
    <div class="container" style="margin-top: 150px;">
      <div class="alert alert-info">
        <strong><h1>Email Verification</h1></strong><p>Please confirm your email address to complete the registration. </p>
      </div>
      
    </div>
{% endblock content %}

ptm/mysite/templates/mysite/acc_active_sent.html
{% extends "base.html" %}
{% load static %}
{% block title %}Email Verification{% endblock %}

{% block register %}
<div class="register-login-area">
                            
        <a href="{% url 'register' %}" class="btn active">Register</a>
        <a href="{% url 'login' %}" class="btn">Login</a>
    
    </div>
{% endblock  %}



{% block content %}
    <link rel="stylesheet" type = "text/css" href="{% static 'music/css/StyleSheet3.css' %}">

    <div class="container" style="margin-top: 150px;">
      <div class="alert alert-info">
        <strong><h1>Email Verification</h1></strong><p>Please confirm your email address to complete the registration. </p>
      </div>
      
    </div>
{% endblock content %}

ptm/mysite/templates/mysite/change_password.html
{% extends "Base.html" %}
{% load static %}
{% block title %}Change Password{% endblock %}
{% block content %}

<div class="mx-auto mt-5" style="width: 400px;">
    <div class="card border-0" style="width: 25rem;">


                <div class="card-body">
                    <h5 class="card-title text-center text-danger font-weight-bold font-size-25">Change Password</h5>
                

                    {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-warning alert-dismissible fade show mx-auto" role="alert">
                            {{ error|escape }}
                        </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}


                <form action="{% url 'change_password' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class = "exampleInputPassword1">Old Password </label>
                        <input type="password" name="old_password" autofocus required id="id_old_password"  class="form-control"  placeholder="Enter Old Password">
                    <div>
                        <br>
                    <div class="form-group">
                        <label class = "exampleInputPassword2">New Password</label>
                        <input type="password" name="new_password1" required id="id_new_password1"  class="form-control"  placeholder="Enter New Password">
                        <small id="passwordHelpInline" class="text-muted">
                                <ul>
                                    <li>Your password can&#39;t be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can&#39;t be a commonly used password.</li>
                                    <li>Your password can&#39;t be entirely numeric.</li>
                                </ul>
                        </small>
                    <div>
                        <br>
                            <div class="form-group">
                                    <label class = "exampleInputPassword3">Confirm New Password</label>
                                    <input type="password" name="new_password2" required id="id_new_password2"  class="form-control"  placeholder="Enter New Confirm Password">
                                <div>
                        <br>
                        <div class="form-group mx-auto text-center">
                            <button type="submit" class="btn btn-danger text-center bg-danger font-weight-bold ml-3">Change Password</button>
                          </div>
                    
                </form>
            </div>
            </div>

        </div>
{% endblock content %}

ptm/mysite/templates/mysite/contact.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Contact {% endblock %}




{% block register %}
{% if request.user.is_authenticated %}
    <div class="register-login-area">
                                
            <a href="{% url 'editProfile'   %}" class="btn text-white">{{ request.user.username}}</a>
            <a href="{% url 'logout' %}" class="btn text-white">Logout</a>
        
        </div>

{% else %}

<div class="register-login-area">
                                
        <a href="{% url 'register' %}" class="btn text-white">SignUp</a>
        <a href="{% url 'login' %}" class="btn text-white">Login</a>
    
    </div>
{% endif %}

    {% endblock  %}






{% block content %}

<br>
<br>
<br>
<br>

    <!-- ##### Contact Area Start ##### -->
    <section class="contact-area">
        <div class="container">
            <div class="row">
                <!-- Contact Info -->
                <div class="col-12 col-lg-6">
                    <div class="contact--info mt-50 mb-100">
                        <h4>Contact Info</h4>
                        <ul class="contact-list">
                            <li>
                                <h6><i class="fa fa-clock-o" aria-hidden="true"></i> Business Hours</h6>
                                <h6>8:00 AM - 4:00 PM</h6>
                            </li>
                            <li>
                                <h6><i class="fa fa-phone" aria-hidden="true"></i> Number</h6>
                                <h6>+64331-4307703</h6>
                            </li>
                            <li>
                                <h6><i class="fa fa-envelope" aria-hidden="true"></i> Email</h6>
                                <h6>abckindergar@gmail.com</h6>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- Contact Form -->
                <div class="col-12 col-lg-6">
                    <div class="contact-form">
                        <h4>Get In Touch</h4>
                        
                        <form action="{% url 'contact' %}" method="post">
                            {% csrf_token %}

                            
                            <div class="row">
                                <div class="col-12 col-lg-6">
                                    <div class="form-group">
                                        <input type="text" name="userName" placeholder="Name" required id="id_userName" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6">
                                    <div class="form-group">
                                        <input type="text" name="email" placeholder="Email" required id="id_email" class="form-control">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <textarea name="body" class="form-control" cols="30" rows="10" placeholder="Message" required id="id_body"></textarea>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn clever-btn w-100">Send</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->


{% endblock %}

ptm/mysite/templates/mysite/editProfileUser.html
{% extends 'base.html' %}

{% block title %}Real State{% endblock %}

{% block content %}

<div class="mx-auto mb-5" style="width: 350px;">
<div class="card" style="width: 22rem;">
    
    <div class="card-body">
      <form action="{% url 'editProfileUSer' %}" method="POST">
        {% csrf_token %}
      <h5 class="card-title font-weight-bold">{{ request.user.username }}</h5>
      <table class="table">
          
          <tbody>
            <tr>
              
              <td>username</td>
              <td><input class="form-control border-0 bg-transparent" name="username" type="text" placeholder="{{ request.user.username }}" value="{{ request.user.username }}" readonly></td>
              
            </tr>

              {% if profile %}
              <tr>
             
                  
                  
                </tr>
                <tr>
              
                    <td>Phone</td>
                    <td>
                            <input class="form-control border-0 bg-transparent" name="contactNumber" type="text" placeholder="{{ profile.contactNumber }}" value="{{ profile.contactNumber }}" >

                    </td>
                    
                    
                  </tr>
                {% endif %}

                <tr>
                    <td colspan="2" class="border-0">
                      <input type="submit" value="Edit Profile Information" class="btn btn-primary">
                    </td>
                  </tr>
                  
          </tbody>
        </table>
      </form>
    </div>
  </div>
</div>
{% endblock %}

ptm/mysite/templates/mysite/register.html
{% extends "base.html" %}
{% block title %}Registration{% endblock %}



{% block content %}


<style>
        input::-webkit-inner-spin-button,
        input::-webkit-outer-spin-button {
                -webkit-appearance: none;
        }

        input[type="number"] {
                -moz-appearance: textfield;
        }

        .font-size-25 {
                font-size: 25px;
        }       

        #signinlink:link {
                text-decoration: underline;
        }

        /* visited link */
        #signinlink:visited {
                text-decoration: underline;
        }

        /* mouse over link */
        #signinlink:hover {
                text-decoration: underline;
        }

        /* selected link */
        #signinlink:active {
                text-decoration: underline;
        }

        .alert{
                width:350px;
        }

        .ml-20{
                margin-left:235px;
        }       

        .font-size-16{
                font-size:16px;
        }

        .font-size-18{
                font-size:18px;
        }

        .font-size-20{
                font-size:20px;
        }

</style>


<div class="mx-auto mt-5" style="width: 550px;">

        {% if messages %}

        <div class="modal" tabindex="-1" role="dialog" id="succesfulsignupmodal">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header border-0">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body mx-auto text-center font-weight-normal font-size-20">
                      <p>Thank you for singing up with UpClinch!</p>
                      <p><a href="." class="card-link text-danger text-decoration-none font-weight-bold" id="signinlink">Complete my profile now</a></p>
                      <p><a href="." class="card-link text-danger text-decoration-none font-weight-bold" id="signinlink">Go to property search</a></p>
                    </div>
                  </div>
                </div>
              </div>

              <script>
                        $('#succesfulsignupmodal').modal('show')

              </script>

        {% endif %}

        <div class="card border-0" style="width: 35rem;">





                <div class="card-body">
                        <h5 class="card-title text-center text-danger font-weight-bold font-size-25">Sign Up with
                                UpClinch</h5>
                        <p class="card-text text-center">Have an account already? <a href="{% url 'login' %}"
                                        class="card-link text-danger text-decoration font-weight-bold" id="signinlink">Sign In</a></p>

                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible mx-auto">
                                <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}

                        {% if form_2.errors %}
                        {% for field in form_2 %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible mx-auto">
                                <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                        {% endfor %}
                        {% endif %}

                        <form action="{% url 'register' %}" method="POST" class="mt-5">
                                {% csrf_token %}
                                
                
                                
                                <div class="form-group row">
                                        <label for="id_username" class="col-sm-3 col-form-label pr-0 text-right">Name  <span class="text-danger font-weight-bold">*</span></label>
                                        <div class="col-sm-7">
                                        <input type="text" name="username" required maxlength="30" id="id_username" autocomplete="off"
                                                class="form-control">
                                        </div>
                                </div>


                                <div class="form-group row">
                                        <label for="id_email" class="col-sm-3 col-form-label pr-0 text-right">Email <span class="text-danger font-weight-bold">*</span></label>
                                        <div class="col-sm-7">
                                        <input type="email" name="email" required id="id_email" class="form-control" autocomplete="off">
                                        </div>
                                </div>
                                <!-- <div class="form-group">
                                <label for="id_username">Username</label>
                                <input type="text" name="username" maxlength="150" required id="id_username"
                                        class="form-control" placeholder="Enter User">
                                <small id="usernameHelpInline" class="text-muted">
                                        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
                                </small>
                        </div> -->


                                <div class="form-group row">
                                        <label for="id_password" class="col-sm-3 col-form-label pr-0 text-right">Password <span class="text-danger font-weight-bold">*</span></label>
                                        <div class="col-sm-7 mr-0">
                                        <input type="password" name="password" required id="id_password"
                                                class="form-control">
                                                
                                        </div>
                                        <div class="col-sm-1 ml-0 pl-0 ml-0 mt-2">
                                                <i class="fas fa-question-circle bg-transparent ml-0 p-0"
                                                style="color: black; background-color: transparent; border: none; font-size: 20px;" data-toggle="popover"
                                                data-placement="right"></i>
                                        </div>

                                </div>

                                <div class="form-group row">
                                        <label for="id_password2" class="col-sm-3 col-form-label pl-0 pr-0 text-nowrap">Confirm Password <span class="text-danger font-weight-bold">*</span></label>
                                        <div class="col-sm-7">
                                        <input type="password" name="password2" required id="id_password2" class="form-control">
                                </div>
                                        
                                </div>

                                <div class="form-group row">
                                        <label for="phone" class="col-sm-3 col-form-label pl-5 pr-2 text-right">Phone</label>
                                        <div class="col-sm-7">
                                        <input type="text" name="phone" id="id_phone" class="form-control" maxlength="11" autocomplete="off">
                                </div>

                                
                                        
                                </div>
                                
                                <div class="form-group row">
                                        <label for="occupation" class="col-sm-3 col-form-label pl-5 pr-2 text-right">Occupation</label>
                                        <div class="col-sm-7">
                                        <input type="text" name="occupation" id="id_occupation" class="form-control" maxlength="200" autocomplete="off">
                                        
                                        
                                </div>
                                </div>

                                <!-- <div class="form-group">
                                        <label for="exampleFormControlSelect2">Buyer or Agent</label>
                                        <select  class="form-control" id="exampleFormControlSelect2" name="Teacher_or_Parent">
                                          <option value="Buyer" selected>Buyer</option>
                                          <option value="Agent">Agent</option>
                                        </select>
                                      </div> -->

                                      <div class="form-group mx-auto text-center">
                                        <button type="submit" class="btn btn-danger text-center bg-danger font-weight-bold ml-5" value="Sign-Up">Sign Up</button>
                                      </div>

                                <div class="form-group row mx-auto text-center">
                                        <p class="card-text text-center mx-auto">By Signing up you agree to our <a href="#"
                                                class="card-link text-danger text-decoration font-weight-bold" id="signinlink">Terms of Service</a> and <a href="#" class="card-link text-danger text-decoration font-weight-bold ml-0" id="signinlink">Privacy Police</a> </p>
                                
                                                
                                        </div>

                                

                        </form>

                </div>
        </div>

</div>



{% endblock %}